# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 12:58
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='Inhalt', to='cms.Placeholder'),
        ),
    ]
