# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('articles', '0002_category_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='articles_categorypluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('number_to_show', models.IntegerField(choices=[(3, '3'), (6, '6'), (9, '9'), (12, '12')], default=6)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
    ]
